version: '3.0'
services:
  rpi-wifi-ap:
    container_name: wifi-ap
    hostname: wifi-ap
    image: namthz/rpi-wifi-ap:latest
    network_mode: host
    privileged: true
    restart: always
    environment:
      INTERFACE: wlan0
      CHANNEL: 6
      SSID: PI
      AP_ADDR: 192.168.254.1
      SUBNET: 192.168.254.0
      WPA_PASSPHRASE: Raspberry@123
      OUTGOINGS: eth0
